'use strict'

exports.BattleTypeChart = {
	"Prism": {
		damageTaken: {
			"Bug": 0,
			"Dark": 0,
			"Dragon": 0,
			"Electric": 0,
			"Fighting": 0,
			"Fire": 0,
			"Fairy": 0,
			"Flying": 0,
			"Ghost": 0,
			"Grass": 0,
			"Ground": 0,
			"Ice": 0,
			"Normal": 0,
			"Poison": 0,
			"Psychic": 0,
			"Rock": 0,
			"Steel": 0,
			"Water": 0,
			"Gas": 0,
			"Sound": 0,
			"Tri": 0,
			"Prism": 0,
		},
	},	
	"Tri": {
		damageTaken: {
			"Bug": 0,
			"Dark": 0,
			"Dragon": 0,
			"Electric": 0,
			"Fighting": 0,
			"Fire": 0,
			"Fairy": 0,
			"Flying": 0,
			"Ghost": 0,
			"Grass": 0,
			"Ground": 0,
			"Ice": 0,
			"Normal": 0,
			"Poison": 0,
			"Psychic": 0,
			"Rock": 0,
			"Steel": 0,
			"Water": 0,
			"Gas": 0,
			"Sound": 0,
			"Tri": 0,
			"Prism": 0,
		},
	},
	"Gas": {
		damageTaken: {
			"Bug": 2,
			"Dark": 0,
			"Dragon": 0,
			"Electric": 0,
			"Fighting": 2,
			"Fire": 1,
			"Fairy": 0,
			"Flying": 0,
			"Ghost": 0,
			"Grass": 1,
			"Ground": 0,
			"Ice": 1,
			"Normal": 0,
			"Poison": 0,
			"Psychic": 0,
			"Rock": 0,
			"Steel": 0,
			"Water": 0,
			"Gas": 0,
			"Sound": 1,
			"Tri": 1,
		},
	},
	"Sound": {
		damageTaken: {
			"Bug": 1,
			"Dark": 0,
			"Dragon": 0,
			"Electric": 1,
			"Fighting": 1,
			"Fire": 2,
			"Fairy": 2,
			"Flying": 0,
			"Ghost": 1,
			"Grass": 1,
			"Ground": 0,
			"Ice": 1,
			"Normal": 1,
			"Poison": 0,
			"Psychic": 0,
			"Rock": 2,
			"Steel": 2,
			"Water": 2,
			"Gas": 2,
			"Sound": 3,
			"Tri": 1,
		},
	},
	"Fire": {
		damageTaken: {
			brn: 3,
			"Bug": 2,
			"Dark": 0,
			"Dragon": 0,
			"Electric": 0,
			"Fairy": 2,
			"Fighting": 0,
			"Fire": 2,
			"Flying": 0,
			"Ghost": 0,
			"Grass": 2,
			"Ground": 1,
			"Ice": 2,
			"Normal": 0,
			"Poison": 0,
			"Psychic": 0,
			"Rock": 1,
			"Steel": 2,
			"Water": 1,
			"Gas": 1,
		},
		HPivs: {"atk":30, "spa":30, "spe":30},
		HPdvs: {"atk":14, "def":12},
	},
	"Fairy": {
		damageTaken: {
			"Bug": 2,
			"Dark": 2,
			"Dragon": 3,
			"Electric": 0,
			"Fairy": 0,
			"Fighting": 2,
			"Fire": 0,
			"Flying": 0,
			"Ghost": 0,
			"Grass": 0,
			"Ground": 0,
			"Ice": 0,
			"Normal": 0,
			"Poison": 1,
			"Psychic": 0,
			"Rock": 0,
			"Steel": 1,
			"Water": 0,
		},
	},
	"Dragon": {
		damageTaken: {
			"Bug": 0,
			"Dark": 0,
			"Dragon": 1,
			"Electric": 2,
			"Fairy": 1,
			"Fighting": 0,
			"Fire": 2,
			"Flying": 0,
			"Ghost": 0,
			"Grass": 2,
			"Ground": 0,
			"Ice": 1,
			"Normal": 0,
			"Poison": 0,
			"Psychic": 0,
			"Rock": 0,
			"Steel": 0,
			"Water": 2,
			"Gas": 0,
			"Sound": 0,
			"Tri": 0,
		},
		HPivs: {"atk":30},
		HPdvs: {"def":14},
	},
}
